import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { outfit, montserrat } from "./font";
//@ts-ignore
import Header from "./components/layout/Header";
import "./globals.css";
import Footer from "./sections/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${montserrat.variable}`}>
      <body
      className="bg-dark relative"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
