"use client";

import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { outfit, montserrat } from "./font";
//@ts-ignore
import Header from "./components/layout/Header";
import "./globals.css";

import Footer from "./sections/footer";
import Menu from "./components/menu";

// export const metadata: Metadata = {
//   title: "Allevent",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showMenu, setShowMenu] = useState(false);

  return (
    <html lang="en" className={`${outfit.variable} ${montserrat.variable}`}>
      <body className="bg-dark relative">
        <Header setShowMenu={setShowMenu} />
        <Menu showMenu={showMenu} setShowMenu={setShowMenu} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
